version: '1.0'
services:
  semar-db:
    image: postgres:13
    ports:
      - '5432:5432'
    restart: always
    volumes:
      - db_data: /var/postgres/db_data
    environment:
      POSTGRES_DB: 'semar'
      POSTGRES_PASSWORD: 'dev123'
  volumes:
      - db_data
